site_name: "Chapa Sirithunge"
site_url: https://chapasirithunge.github.io
site_author: Chapa Sirithunge
site_description: "That's moi!"
copyright: Chapa Sirithunge
theme:
  #favicon: assets/images/logo.png
  icon:
    logo: material/robot-excited-outline
  name: material
  #custom_dir: docs/overrides
  font:
    text: Noto Sans
  features:
    - header.autohide
    - navigation.tabs
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: slate
      primary: lime
      accent: deep orange

nav:
  - About Me: 
    - index.md
    - Talks: Talks.md
    - Events: Events.md
    - News:  News.md
  - Projects:
    - projects/index.md
    - Robotic Patients: projects/Robotic_Patients.md
    - Soft Robotics: projects/Soft_Manipulation.md
    - Service Robots: projects/Service_robots.md
  - Robotics for humanity: Robotics_for_humanity.md
  - Networks: Networks.md
  - Blog:
    - blog/index.md

plugins:
  - search
  - blog
  
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg